USE [master]
GO

/****** Object:  Database [TDVK22CNT3Lesson09Db]    Script Date: 6/26/2024 11:19:55 AM ******/
CREATE DATABASE [TDVK22CNT3Lesson09Db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TDVK22CNT3Lesson09Db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DUYVU\MSSQL\DATA\TDVK22CNT3Lesson09Db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TDVK22CNT3Lesson09Db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.DUYVU\MSSQL\DATA\TDVK22CNT3Lesson09Db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TDVK22CNT3Lesson09Db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET ARITHABORT OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET RECOVERY FULL 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET  MULTI_USER 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TDVK22CNT3Lesson09Db] SET  READ_WRITE 
GO

