//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDVK22CNT3Lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDVAccount
    {
        public string TDVId { get; set; }
        public string TDVUserName { get; set; }
        public string TDVPassword { get; set; }
        public string TDVFullName { get; set; }
        public string TDVEmail { get; set; }
        public Nullable<bool> TDVActive { get; set; }
    }
}
