//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDVK22CNT3Lesson11_2210900138.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TDVK22CNT3Lesson11DbEntities : DbContext
    {
        public TDVK22CNT3Lesson11DbEntities()
            : base("name=TDVK22CNT3Lesson11DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TDVCategory> TDVCategories { get; set; }
        public virtual DbSet<TDVProduct> TDVProducts { get; set; }
    }
}
