//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDVK22CNT3Lesson11_2210900138.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TDVCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDVCategory()
        {
            this.TDVProducts = new HashSet<TDVProduct>();
        }
        [Display(Name ="Ma danh muc")]
        public int TDVId { get; set; }
        [Display(Name = "Ten danh muc")]
        public string TDVCateName { get; set; }
        [Display(Name = "Trang thai")]
        public Nullable<bool> TDVStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDVProduct> TDVProducts { get; set; }
    }
}
