//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDVK22CNT3Lesson11_2210900138.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDVProduct
    {
        public string TDVId2210900138 { get; set; }
        public string TDVProName { get; set; }
        public Nullable<int> TDVQty { get; set; }
        public Nullable<double> TDVPrice { get; set; }
        public Nullable<int> TDVCateId { get; set; }
        public Nullable<bool> TDVActive { get; set; }
    
        public virtual TDVCategory TDVCategory { get; set; }
    }
}
