//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDVLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDVKetqua
    {
        public string TDVMaSV { get; set; }
        public string TDVMaMH { get; set; }
        public Nullable<int> Diem { get; set; }
    
        public virtual TDVMonHoc TDVMonHoc { get; set; }
        public virtual TDVSinhVien TDVSinhVien { get; set; }
    }
}
