//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDVLesson09.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDVSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDVSinhVien()
        {
            this.TDVKetquas = new HashSet<TDVKetqua>();
        }
    
        public string TDVMaSV { get; set; }
        public string TDVHoSV { get; set; }
        public string TDVTenSV { get; set; }
        public Nullable<bool> TDVPhai { get; set; }
        public Nullable<System.DateTime> TDVNgaySinh { get; set; }
        public string TDVNoiSinh { get; set; }
        public string TDVMaKH { get; set; }
        public string TDVHocBong { get; set; }
        public Nullable<decimal> TDVDiemTrungBinh { get; set; }
    
        public virtual TDVKhoa TDVKhoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDVKetqua> TDVKetquas { get; set; }
    }
}
